version: "3.9"
services:

  my-tasks-manager-api:
    build:
      context: .
    ports:
      - '3000:3000'
    env_file: ./.env
    environment:
      - DB_CONNECTION=$DB_CONNECTION
    volumes:
    - .:/app
    - /app/node_modules
    command: npm run start:dev
